### PR TITLE
Make a setup script

### PR DESCRIPTION
**Pull request by evokerking1**
Added a script that does all the node/npm commands

### CODE REVIEW

**Comment by evokerking1** [comment]
> Hey, it would be great if u add a full setup with like a web installer to this pr. I also can help you to complete this pr.

would love the help!!

**Comment by evokerking1** [comment]
Made a json config schema

**Comment by evokerking1** [comment]
butt how do we give a user admin without having admin?

**Comment by evokerking1** [comment]
@privt00

**Comment by privt00** [comment]
> butt how do we give a user admin without having admin?

By setting isAdmin in the db to 1

**Comment by evokerking1** [comment]
removed a security vulnerability

**Comment by evokerking1** [comment]
why did thank you close this pr

**Pull request closed without merging**
